### ISSUE TITLE
EPIC: Online aanvragen opslaan voor Mijn Nijmegen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/webformulieren-submissionstorage#1]
Om online aanvragen te kunnen tonen moeten deze in een bruikbaar formaat opgeslagen worden. Deze epic heeft tot doel de opslag van inzendingen te organiseren, zodat bij het tonen hiervan in (bijv.) Mijn Nijmegen al zoveel mogelijk gegevens beschikbaar zijn. Lees het [ontwerp](https://github.com/GemeenteNijmegen/devops/blob/master/mijnnijmegen/webformulier-aanvragen-in-mijn-nijmegen.md#inrichting-inzendingen-opslag) voor details.

```[tasklist]
### Bouw storage-oplossing
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/2
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/3
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/5
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/6
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/7
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/8
```

**Comment by joostvanderborg** [comment]
Epic afgerond. Verbetermogelijkheden:
- s3.copyObject gebruiken als we naar nieuwe LZ zijn (nu teveel gedoe)
- uploads worden nu door de lambda gedaan, op queue zetten en 1 voor 1 verwerken? (robuuster)
- DynamoDB kan nu op user of inzending bekeken, zit nog geen datumveld of iets dergelijks in.
