### ISSUE TITLE
Files behorende bij inzendingen kunnen ophalen en opslaan in S3

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/webformulieren-submissionstorage#7]
```[tasklist]
### Tasks
- [x] cross-account toegang voor lambda functie
- [x] testen kopiëren objecten van s3->s3
- [x] inbouwen in save()-method
- [ ] https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/10
```

**Comment by joostvanderborg** [comment]
Werkt nog niet: copy command kan niet cross-region, en webformulieren staat nog in eu-west-1. Ombouwen naar ouderwetse get/put versie.

**Comment by joostvanderborg** [comment]
kms-access lijkt niet te mogen, iets met de SCP. Met Xenia bespreken.
